# Generated by Django 4.2 on 2023-04-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_item_image_alter_userextend_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='base.item'),
        ),
    ]
