# Generated by Django 4.2 on 2023-05-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_images_rename_image_item_thumbnail_item_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to='base.images'),
        ),
    ]
