# Generated by Django 4.2 on 2023-05-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_item_images_images_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='item',
            new_name='img',
        ),
    ]
