# Generated by Django 4.2 on 2023-05-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_notification_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
