# Generated by Django 4.2 on 2023-05-08 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_remove_userextend_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='img',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notify',
        ),
        migrations.AddField(
            model_name='images',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img', to='base.item'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notify', to=settings.AUTH_USER_MODEL),
        ),
    ]
