# Generated by Django 4.2 on 2023-05-10 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_images_img_remove_notification_notify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img', to='base.item'),
        ),
    ]
